---
title: "Syllabus"
format: 
  revealjs:
    code-fold: false
    theme: white
    footer: "GEO4251 Climate Change & Storms"
    chalkboard: true
editor: source
---

## GEO4251: Climate Change & Storms

-   Understanding storms and their relationship to our changing climate through the analysis of data

## Contact information

-   {{< fa chalkboard-user >}} Professor James B. Elsner
-   Bellamy {{< fa building >}} Room 314
-   Lesson {{< fa clock >}} MW 3:05-4:20 p.m.
-   Student {{< fa clock >}} TR 9:15-9:45 a.m., MW 2:15-3 p.m.
-   {{< fa envelope >}} jelsner@fsu.edu

## Who am I?

-   [{{< fa house size=1x >}}](http://myweb.fsu.edu/jelsner/_site/) Web
-   [{{< fa graduation-cap size=1x >}}](https://scholar.google.com/citations?user=uF8tRWQAAAAJ) Research
-   [{{< fa brands github size=1x >}}](https://github.com/jelsner/) Code
-   [{{< fa brands mastodon size=1x >}}](https://fediscience.org/@jelsner) Social
-   [[{{< fa brands youtube size=1x >}}](https://www.youtube.com/channel/UCmvKrcWTnNGjoy9OTGTz1qQ)]{style="color:red"} Play

## Description

-   This course is for students who want to learn about the relationships between climate change and Earth's most powerful storms through the analysis and modeling of data

-   All course materials are available on GitHub {{< fa brands github >}} <https://github.com/jelsner/CCS-2023>

## Expected learning outcomes

-   On successful completion of this course, you will be able to:

1.  Appraise the fundamental concepts, principles, theories, and terminology used in discussing the relationships between climate change and storminess
2.  Apply the principles of data science to make effective graphs, tables and inferences
3.  Contribute to contemporary scientific debates using empirical evidence

## Materials and class meetings

-   Computer and access to the internet
-   Course slides are available through [GitHub](https://github.com/jelsner/CCS-2023/)
-   No textbook is required

## Class meetings

-   Each class period I will prepare a set of slides using [Quarto](https://quarto.org/). Quarto is an open-source scientific publishing system

-   Quarto allows me to weave together narrative text and code to produce formatted output. Quarto documents are reproducible

-   The slides (`_.qmd` files) are available on GitHub. The slide files are opened using an application called RStudio

-   In-person lessons will be held in this room (Bellamy 208)

## Grading

-   You are responsible for:

1.  Reading, watching, and running code in the lesson slides. You can do this during class or outside the classroom. I will not take attendance
2.  Completing and returning the in-class labs on time

-   Grades are determined by how well you do on the labs using the following standard

## Standard

-   A: Outstanding: few, in any, errors/omissions
-   B: Good: only minor errors/omissions
-   C: Satisfactory: minor omissions, at least one major error/omission
-   D: Poor: several major errors/omissions
-   F: Fail: many major errors/omissions

I will use the +/- system

Grades will be posted as they are recorded on [FSU Canvas](https://canvas.fsu.edu)

## Academic honor code

-   <https://fda.fsu.edu/academic-resources/academic-integrity-and-grievances/academic-honor-policy>

-   Americans With Disabilities Act: Students with disabilities needing academic accommodation should: (1) register with and provide documentation to the Student Disability Resource Center; (2) bring a letter indicating the need for accommodation and what type. This should be done during the first week of classes.

## Diversity and inclusiveness

-   It is my intent to present notes and data that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture

## Schedule

| Dates   | Lessons| Topics  |
|---------|--------|---------|
| 1/9-2/1 | 1-6    | Getting setup, R, working with data |
| 2/6-13  | 7-9    | Making graphs, quantifying trends   |
| 2/15-3/1| 10-14  | Weather/climate data, climate change|
| 3/6-27  | 15-18  | Climate swings, hurricane analytics |
| 3/29-4/5| 19-21  | Hurricane analytics |
| 4/10-26 | 22-26  | Tornado analytics |

## 

26 dates: 20 lesson days + 6 lab days

| Lab | Date                 | Lessons covered |
|-----|----------------------|-----------------|
| 1   | Wednesday February 1 | 1-5             |
| 2   | Monday February 13   | 7-8             |
| 3   | Wednesday March 1    | 10-13           |
| 4   | Monday March 27      | 15-17           |
| 5   | Wednesday April 5    | 19-20           |
| 6   | Wednesday April 19   | 22-24           |

## Hardware and software

-   You will need a laptop computer running either Windows, MacOS, or Linux. I use MacOS
-   The class notes live on [GitHub](https://github.com/jelsner/CCS-2023/)
-   Class notes are on slides made with an open-source scientific publishing system called _Quarto_
-   Coding will be done in _R_ through _RStudio_

## Getting set up

-   Go to https://github.com/jelsner/CCS-2023
-   Follow instructions in the `README.md` file
-   I will walk you through this on Wednesday

## Our warming planet

{{< video https://www.youtube.com/embed/haBG2IIbwbA >}} 30 seconds

-   First-day attendance sign-in
