---
title: "Lab 1"
author: "PUT YOUR NAME HERE"
format: html
editor: source
date: February 1, 2023
---

Due: 4:30 p.m. February 1, 2023

Total Points: 18

Enter your answers below each question in the `.qmd` file. The number in parentheses after the question is the maximum number of points. When finished submit your `.qmd` file through Canvas

## 1

Write code to get the tornado data (from file `Tornadoes.csv` in the directory `data`) into your R environment as a data frame called `Torn.df` (4)
```{r}

```


## 2

Write code to get the average tornado path length. The path length variable is `len` in `Torn.df` from question 1 (4)

## 3

Write code to create a new data frame from `Torn.df` containing only tornadoes with damage rating (`mag`) greater or equal to 4 (4)

## 4

Write code to make the functions from the {ggplot2} package available to your current R session (4)

## 5

Type your answers below to the following questions: According to the PBS video entitled "What is the riskiest region in the US as the climate changes?" (linked in the file `05-working-with-data.qmd`), what state has the county with the highest overall risk resulting from climate change? What is the name of the county? (2)
