---
title: "Hurricane analytics: intensity"
format:
  revealjs:
    slide-number: c/t
    code-fold: false
    chalkboard: true
editor: source
editor_options: 
  chunk_output_type: console
---

##  {.smaller}

-   Import the IBTrACS Atlantic hurricane csv file

```{r, eval=FALSE}
#| echo: true
L <- "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/csv/ibtracs.NA.list.v04r00.csv"

NA.df <- readr::read_csv(file = L,
                         show_col_types = FALSE) |>
  dplyr::filter(SEASON != "Year") |>
  dplyr::mutate(Season = as.integer(SEASON)) |>
  dplyr::filter(Season >= 1950) |>
  dplyr::mutate(Time = as.Date(ISO_TIME),
                W_kt = as.numeric(USA_WIND),
                W_mps = W_kt * .5144447) |>
  dplyr::select(SID, Season, BASIN, NAME, Time, W_kt, W_mps)

readr::write_csv(NA.df, 
                 file = here::here("data", "NA.csv"))
```

## 

-   Get wind speed quantiles for tropical cyclones with winds at least 33 m/s. First get per storm fastest wind speed

```{r}
#| echo: true
NA.df <- readr::read_csv(file = here::here("data", "NA.csv"),
                         show_col_types = FALSE)

LMI.df <- NA.df |>
  dplyr::group_by(SID) |>
  dplyr::summarize(Year = dplyr::first(Season),
                   Name = dplyr::first(NAME),
                   MaxW_mps = max(W_mps)) |>
  dplyr::filter(MaxW_mps >= 33)
```

## Frequency

```{r}
Frequency.df <- LMI.df |>
  dplyr::group_by(Year) |>
  dplyr::summarize(nH = dplyr::n())

ggplot(data = Frequency.df,
       mapping = aes(x = Year, y = nH)) +
  geom_line() +
  geom_smooth(method = lm) 
```

## 

Increases in the number of hurricanes

```{r}
#| echo: true
glm(nH ~ Year, data = Frequency.df, family = poisson)
```

.004 implies xx \* (1 + .004)\^ny =

## Intensity

```{r}
#| echo: true
Intensity.df <- LMI.df |>
  dplyr::group_by(Year) |>
  dplyr::summarize(q90 = quantile(MaxW_mps, probs = .9),
                   q75 = quantile(MaxW_mps, probs = .75),
                   q50 = quantile(MaxW_mps, probs = .5)) |>
  tidyr::pivot_longer(cols = 2:4, names_to = "Level", values_to = "Quantile")


ggplot(data = Intensity.df,
       mapping = aes(x = Year, y = Quantile, color = Level)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE) 
```

## 

```{r}
#| echo: true
ggplot(data = LMI.df,
       mapping = aes(x = Year, y = MaxW_mps)) +
  geom_point() +
  geom_smooth(method = lm)
```

## 

```{r}
#| echo: true
ggplot(data = LMI.df,
       mapping = aes(y = MaxW_mps, x = Year, group = Year)) +
  geom_boxplot()
```

```{r}
#| echo: true

summary(quantreg::rq(MaxW_mps ~ Year, tau = .9, data = LMI.df))

plot(quantreg::rq(MaxW_mps ~ Year, tau = -1, data = LMI.df))
```
