---
title: "Syllabus"
format: 
  revealjs:
    code-fold: false
    theme: white
    footer: "GEO4251 Climate Change & Storms"
    chalkboard: true
editor: source
---

## GEO4251: Climate Change & Storms

Understanding connections between our changing climate & storminess through analysis of data

## Contact information

{{< fa chalkboard-user >}} Professor James B. Elsner (he/his/him)

Bellamy {{< fa building >}} Room 314

Lesson {{< fa clock >}} MW 3:05-4:20 p.m.

Student {{< fa clock >}} TR 9:15-10:30 a.m.

{{< fa envelope >}} [jelsner\@fsu.edu](mailto:jelsner@fsu.edu){.email}

## Who am I?

[{{< fa house >}}](http://myweb.fsu.edu/jelsner/_site/)
[{{< fa brands github >}}](https://github.com/jelsner/)
[{{< fa brands mastodon >}}](https://fediscience.org/@jelsner)

## Course description

This course is for students who want to learn about the relationships between climate change and Earth's most powerful storms through the analysis and modeling of data.

All the course slides are available on GitHub {{< fa brands github >}}  <https://github.com/jelsner/CS-2023>

## Expected learning outcomes

On successful completion of this course, you will be able to:

1. Appraise the fundamental concepts, principles, theories, and terminology used in discussing the relationships between climate change and storminess
2. Apply the principles of data science to make effective graphs, tables and inferences on this topic
3. Contribute to contemporary scientific debates on this topic with empirical evidence

## Materials and class meetings {.unnumbered}

-   Access to the internet and a computer
-   Course slides are available through GitHub  <https://github.com/jelsner/CS-2023>
-   No textbook is required

## Class meetings

Each class period I will prepare a small set of slides using [Quarto](https://quarto.org/). Quarto is an open-source scientific publishing system. 

Quarto allows me to weave together narrative text and code to produce formatted output. Quarto documents are reproducible.

The slides (`_.qmd` files) are available on GitHub. The slide files are opened using the RStudio application. 

In-person lessons will be held in this room (Bellamy 208).

## Grading

You are responsible for:

1.  Reading, watching, and working through the code in the lesson slides. You can do this during the lessons as I talk or outside the classroom. I will not take attendance
2.  Completing and returning the in-class exercises on time

Grades are determined by how well you do on the in-class exercises using the following standard.

## Standard

-   A: Outstanding: few, in any, errors/omissions
-   B: Good: only minor errors/omissions
-   C: Satisfactory: minor omissions, at least one major error/omission
-   D: Poor: several major errors/omissions
-   F: Fail: many major errors/omissions

I'll use the +/- system.

Outline of topics

## Getting comfortable

-   Getting set up
-   R & RStudio
-   Scientific workflow
-   Data science

## Climate data

-   Pre-analyzed data
-   CO2 concentration
-   Sea ice and sea levels
-   Temperatures: ocean, land, global vs local
-   Proxy data: ice cores, over-wash sediment deposits, tree rings
-   Humidity
-   Storms: hurricanes, tornadoes
-   Modes of variability

## Analyzing climate data

-   Statistics vs observations
-   Detection vs attribution
-   Plots and graphs
-   Frequency vs intensity

## Modeling climate data

-   Regression trends
-   Uncertainty: classical vs Bayesian
-   Space vs time

## Climate models

-   Detection vs attribution
-   Prediction vs predictability
-   Prediction markets